### ISSUE TITLE
Thoughts about allowing for multiple bundle groupings?

### ISSUE THREAD

**Issue by rmanalan** [quirkey/jim#10]
Sorry for posting this as an issue, but there doesn't seem to be a Jim group.  Anyway, I like the focus and conciseness of Jim, but need a bit more flexibility.  I was on my way to building a JS/CSS packager similar to Jim but it looks like Jim can do most of what I need except currently it doesn't package CSS and everything gets bundled to one file.  I would love to be able to have multiple groups of JS/CSS files to be bundled.  Currently, Jim uses a very simple config format... to support multiple groups, we'd have to move to using something like Yaml or JSON for the config:

```
{
    "base.js": [
        "js/vendor/jquery.js",
        "js/vendor/sammy.js",
        "js/vendor/myapp.js"
    ],
    "plugins.js": [
        "js/plugins/component1.js",
        "js/plugins/component2.js"
    ],
    "styles.css": [
        "css/reset.css",
        "css/styles.css"
    ]
}
```

What do you think?  Is this something you'd want to see in Jim also?

**Comment by quirkey** [comment]
Hey rich

this is actually very close to what I was thinking for the next version of jim. I also want multiple bundles and I think JSON makes sense as the Jimfile format (the format there now is silly and was really just the fastest/simplest thing possible for me). The only adjustment I would make was that we would need to support specific versions for the files, too. What do you think about this:

```
    {
      "base": [
          ["js/vendor/jquery.js", "1.4.4"],
          ["js/vendor/sammy.js", "0.6.4"],
          "js/vendor/myapp.js"
      ],
      "plugins": [
          "js/plugins/component1.js",
          "js/plugins/component2.js"
      ]
    }
```

This kind of changes the way compress would work, too. What do you think about having it compress all the files with "bundlename.min.js"? that probably makes a lot of sense. 

The one thing I havent really thought about is CSS bundling. Personally I probably wouldnt use it because I use SASS/SCSS on most projects these days and it does that for you. I understand the need, though, I'm just having trouble figuring out how it would fit in with the current structure. Would you just use it for bundling CSS in the current dir? Or would you actually want to install, version, and vendor the CSS?

**Comment by rmanalan** [comment]
Great... for flexibility, I'm thinking that the bundle name can either be a simple name like  "base" or a file path "js/base.js" or "css/styles.css."  If a file path is used, we can use the extension to determine how to deal with it (i.e., yui css compress or closure compile js).

As an added bonus, we should support an autogen'd HTML5 cache manifest which can be controlled through the config file as well -- using dttm as version:

```
{
    "manifest": {
        "enabled": true,
        "file": "cache.manifest"
    }
...
}
```

That's probably too verbose, but you get the idea.  The tricky part to this is that we'd have to scrape the html and css for background images.

As far as CSS bundling.  I prefer to do old school CSS so no SASS/SCSS for me... but if we support the path style declaration, bundling them should be no issue.  I don't think Jim needs to support CSS package management.

BTW, what do you think of the "watcher" patches I submitted.  Seems like a good fit for Jim.  I was originally thinking that a smart LABjs or requirejs was what I needed (https://gist.github.com/599562), but with a fs watcher to do dynamic bundling, you get the same thing in a much more streamlined way.

**Comment by quirkey** [comment]
So I just pushed a strong start to this that I've been working on over the weekend. It supports multiple bundles with a JSON jimfile and a bunch of other changes. I also pulled and modified your `watch` patch. I'm really happy with where this is going. Thanks!

**Comment by rmanalan** [comment]
Excellent.  I'll pull and see if there's an elegant way to hack in the css and manifest support.  Also, what do you think of changing the Jimfile name to jimfile.json or something like that... so that my editor knows what type of file it is?
